spring.application.name=trailr-backend

spring.datasource.url=jdbc:mysql://localhost:3306/trailr_db
spring.datasource.username=root
spring.datasource.password=Rollo123$

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true